# See https://hub.docker.com/_/mariadb

# See README.md

# sudo docker network inspect deil_default

# sudo docker-compose -f db.docker-compose.yml up --build --remove-orphans
#

version: '3'
services:
  # MariaDB DB
  # sudo docker exec -it deil_db /bin/bash
  # mysql -uroot -ppassword
  # show databases;
  # use deil;
  # show tables;
  db:
    hostname: localhost
    container_name: deil_db
    build:
      context: .
      dockerfile: ./db.Dockerfile
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE} # CREATE DATABASE deil;
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD} # CREATE USER 'deil' IDENTIFIED BY 'password'; GRANT ALL ON *.* TO 'deil'@'%';
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
